# coding: utf-8

"""
    Clash Royale API

    null  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clashroyale_sdk
from clashroyale_sdk.models.location_list import LocationList  # noqa: E501
from clashroyale_sdk.rest import ApiException


class TestLocationList(unittest.TestCase):
    """LocationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationList(self):
        """Test LocationList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clashroyale_sdk.models.location_list.LocationList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
