# coding: utf-8

"""
    Clash Royale API

    null  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clashroyale_sdk
from clashroyale_sdk.models.player_detail_icon_urls import PlayerDetailIconUrls  # noqa: E501
from clashroyale_sdk.rest import ApiException


class TestPlayerDetailIconUrls(unittest.TestCase):
    """PlayerDetailIconUrls unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerDetailIconUrls(self):
        """Test PlayerDetailIconUrls"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clashroyale_sdk.models.player_detail_icon_urls.PlayerDetailIconUrls()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
