# coding: utf-8

"""
    Clash Royale API

    null  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clashroyale_sdk
from clashroyale_sdk.models.tournament import Tournament  # noqa: E501
from clashroyale_sdk.rest import ApiException


class TestTournament(unittest.TestCase):
    """Tournament unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTournament(self):
        """Test Tournament"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clashroyale_sdk.models.tournament.Tournament()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
