# coding: utf-8

"""
    Clash Royale API

    null  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clashroyale_sdk
from clashroyale_sdk.api.locations_api import LocationsApi  # noqa: E501
from clashroyale_sdk.rest import ApiException


class TestLocationsApi(unittest.TestCase):
    """LocationsApi unit test stubs"""

    def setUp(self):
        self.api = clashroyale_sdk.api.locations_api.LocationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_clan_ranking(self):
        """Test case for get_clan_ranking

        Get clan rankings for a specific location  # noqa: E501
        """
        pass

    def test_get_clan_wars_ranking(self):
        """Test case for get_clan_wars_ranking

        Get clan war rankings for a specific location  # noqa: E501
        """
        pass

    def test_get_location(self):
        """Test case for get_location

        Get location information  # noqa: E501
        """
        pass

    def test_get_locations(self):
        """Test case for get_locations

        List locations  # noqa: E501
        """
        pass

    def test_get_player_ranking(self):
        """Test case for get_player_ranking

        Get player rankings for a specific location  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
