# coding: utf-8

"""
    Clash Royale API

    null  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clashroyale_sdk
from clashroyale_sdk.models.upcoming_chests_list import UpcomingChestsList  # noqa: E501
from clashroyale_sdk.rest import ApiException


class TestUpcomingChestsList(unittest.TestCase):
    """UpcomingChestsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpcomingChestsList(self):
        """Test UpcomingChestsList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clashroyale_sdk.models.upcoming_chests_list.UpcomingChestsList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
