# coding: utf-8

"""
    Clash Royale API

    null  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clashroyale_sdk
from clashroyale_sdk.models.clan_wars_ranking_list import ClanWarsRankingList  # noqa: E501
from clashroyale_sdk.rest import ApiException


class TestClanWarsRankingList(unittest.TestCase):
    """ClanWarsRankingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testClanWarsRankingList(self):
        """Test ClanWarsRankingList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clashroyale_sdk.models.clan_wars_ranking_list.ClanWarsRankingList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
