# coding: utf-8

"""
    Clash Royale API

    null  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clashroyale_sdk
from clashroyale_sdk.models.player_base import PlayerBase  # noqa: E501
from clashroyale_sdk.rest import ApiException


class TestPlayerBase(unittest.TestCase):
    """PlayerBase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlayerBase(self):
        """Test PlayerBase"""
        # FIXME: construct object with mandatory attributes with example values
        # model = clashroyale_sdk.models.player_base.PlayerBase()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
