# coding: utf-8

"""
    Clash Royale API

    null  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import clashroyale_sdk
from clashroyale_sdk.api.tournaments_api import TournamentsApi  # noqa: E501
from clashroyale_sdk.rest import ApiException


class TestTournamentsApi(unittest.TestCase):
    """TournamentsApi unit test stubs"""

    def setUp(self):
        self.api = clashroyale_sdk.api.tournaments_api.TournamentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_tournament(self):
        """Test case for get_tournament

        Get tournament information  # noqa: E501
        """
        pass

    def test_search_tournaments(self):
        """Test case for search_tournaments

        Search tournaments  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
